# Generated by Django 3.1.3 on 2020-11-28 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201125_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time_signed',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 39, 2, 973177), verbose_name='time updated'),
        ),
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 39, 2, 973177), verbose_name='timeframe relevancy end'),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 39, 2, 973177), verbose_name='timeframe relevancy start'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_signed',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 39, 2, 973177), verbose_name='time posted'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_updated_last',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 39, 2, 973177), verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 39, 2, 910660), verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='show_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='time_signed',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 39, 2, 910660), verbose_name='sign up time'),
        ),
    ]
