# Generated by Django 3.1.3 on 2021-01-10 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('time_signed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time updated')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=15, null=True, verbose_name='gender')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='birth date')),
                ('show_email', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('show_phone', models.BooleanField(default=False)),
                ('telegram', models.CharField(blank=True, max_length=15)),
                ('show_telegram', models.BooleanField(default=False)),
                ('other_contact', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=1023)),
                ('points', models.IntegerField(default=0)),
                ('rating_sum', models.IntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('unread_notifications', models.IntegerField(default=0)),
                ('is_representative', models.BooleanField(default=False)),
                ('certificate', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='title')),
                ('post_type', models.CharField(choices=[('Request Assistance', 'Request Assist'), ('Offer Assistance', 'Offer Assist'), ('Group Assistance Request', 'Group Assist Request'), ('Group Assistance Offer', 'Group Assist Offer')], default='Request Assistance', max_length=63, null=True, verbose_name='post type')),
                ('post_status', models.CharField(choices=[('Active', 'Active'), ('Transaction', 'Transaction'), ('Archive', 'Archive')], default='Active', max_length=15, null=True, verbose_name='post status')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time posted')),
                ('time_updated_last', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated')),
                ('location', models.CharField(max_length=63)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='relevant from')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='relevant until')),
                ('equipment', models.TextField(blank=True, max_length=255, verbose_name='equipment details')),
                ('content', models.TextField(max_length=1023)),
                ('approved_reactions', models.ManyToManyField(blank=True, related_name='approved_reactions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='homepage.category')),
                ('reacted_user_rate', models.ManyToManyField(blank=True, related_name='reacted_user_rate', to=settings.AUTH_USER_MODEL)),
                ('reactions', models.ManyToManyField(blank=True, related_name='reactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('users_assist', models.ManyToManyField(blank=True, related_name='users_assist', to=settings.AUTH_USER_MODEL)),
                ('users_to_rate', models.ManyToManyField(blank=True, related_name='users_to_rate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, default='', max_length=255, verbose_name='notification')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='alert_time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
