# Generated by Django 3.1.3 on 2020-11-28 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20201128_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_signed',
        ),
        migrations.AddField(
            model_name='user',
            name='time_registered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 18, 30, 19, 176078, tzinfo=utc), verbose_name='registered time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='time_signed',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 18, 30, 19, 234064, tzinfo=utc), verbose_name='time updated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 18, 30, 19, 234064, tzinfo=utc), verbose_name='timeframe relevancy end'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 18, 30, 19, 234064, tzinfo=utc), verbose_name='timeframe relevancy start'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_signed',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 18, 30, 19, 234064, tzinfo=utc), verbose_name='time posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_updated_last',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 18, 30, 19, 234064, tzinfo=utc), verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 18, 30, 19, 176078, tzinfo=utc), verbose_name='birth date'),
        ),
    ]
