# Generated by Django 3.1.3 on 2020-11-29 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20201130_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='time_signed',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 23, 6, 25, 947489, tzinfo=utc), verbose_name='time updated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 23, 6, 25, 948468, tzinfo=utc), verbose_name='timeframe relevancy end'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 23, 6, 25, 948468, tzinfo=utc), verbose_name='timeframe relevancy start'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 23, 6, 25, 948468, tzinfo=utc), verbose_name='time posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_updated_last',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 23, 6, 25, 948468, tzinfo=utc), verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='post_type',
            field=models.CharField(max_length=15, verbose_name='post type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 23, 6, 25, 946490, tzinfo=utc), verbose_name='birth date'),
        ),
    ]
