# Generated by Django 3.1.3 on 2020-12-18 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0028_auto_20201215_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
