# Generated by Django 3.1.3 on 2020-12-25 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0029_post_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved_reactions',
            field=models.ManyToManyField(blank=True, related_name='approved_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='birth date'),
        ),
    ]
