# Generated by Django 3.1.3 on 2020-12-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_auto_20201226_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Transaction'), ('3', 'Archive')], default='1', max_length=15, null=True, verbose_name='post status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('1', 'Request Assistance'), ('2', 'Offer Assistance')], default='1', max_length=15, null=True, verbose_name='post type'),
        ),
    ]
