# Generated by Django 3.1.3 on 2020-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_auto_20201226_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Transaction', 'Transaction'), ('Archive', 'Archive')], default='Active', max_length=15, null=True, verbose_name='post status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Request Assistance', 'Request Assist'), ('Offer Assistance', 'Offer Assist'), ('Group Assistance Request', 'Group Assist Request'), ('Group Assistance Offer', 'Group Assist Offer')], default='Request Assistance', max_length=63, null=True, verbose_name='post type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=15, null=True, verbose_name='gender'),
        ),
    ]
