# Generated by Django 3.1.3 on 2020-12-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_auto_20201226_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, max_length=255, verbose_name='notification')),
                ('link', models.URLField(blank=True, max_length=255, verbose_name='link')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='unread_notifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='homepage.Message'),
        ),
    ]
