# Generated by Django 3.1.3 on 2020-12-27 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0035_auto_20201227_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications',
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='alert_time'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='reacted_user_rate',
            field=models.ManyToManyField(blank=True, related_name='reacted_user_rate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='users_to_rate',
            field=models.ManyToManyField(blank=True, related_name='users_to_rate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='link',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='message',
            name='notification',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='notification'),
        ),
    ]
