# Generated by Django 3.1.3 on 2021-01-01 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0038_auto_20201230_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_assist',
            field=models.ManyToManyField(blank=True, related_name='users_assisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
