# Generated by Django 3.1.3 on 2021-01-01 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0039_auto_20210102_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_assist',
            field=models.ManyToManyField(blank=True, related_name='users_assist', to=settings.AUTH_USER_MODEL),
        ),
    ]
