# Generated by Django 3.1.3 on 2021-01-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0040_auto_20210102_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='link'),
        ),
    ]
