# Generated by Django 3.1.3 on 2021-01-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0041_auto_20210102_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_representative',
            field=models.BooleanField(default=False),
        ),
    ]
