# Generated by Django 3.1.3 on 2021-01-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0042_profile_is_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
    ]
